#!/usr/bin/env bash
set -eo pipefail

OS="$(uname -s)"
current_script_path=$(readlink -f "${BASH_SOURCE[0]}")
current_script_dir=$(dirname "$current_script_path")

source "$current_script_dir/messages"

function __backup_dir() {
    local src="$1"

    if [ ! -d "$src" ]; then
        return
    fi

    mkdir -p "$src.old"
    msg "Backing up old $src to $src.old"

    if command -v rsync &>/dev/null; then
        rsync --archive --quiet --backup --partial --copy-links --cvs-exclude "$src"/ "$src.old"
    else
        case "$OS" in
            Darwin)
                cp -R "$src/." "$src.old/."
                ;;
            *)
                cp -r "$src/." "$src.old/."
                ;;
        esac
    fi
}
