#!/usr/bin/env bash
set -eo pipefail

function msg() {
    local text="$1"
    local div_width="80"
    printf "%${div_width}s\n" ' ' | tr ' ' -
    echo -e "$text"
}

function info_msg() {
    msg "$(printf "\e[1;34m%s\e[0m\n" "$1")"
}

function warn_msg() {
    msg "$(printf "\e[1;33m%s\e[0m\n" "$1")"
}

function error_msg() {
    msg "$(printf "\e[1;31m%s\e[0m\n" "$1")"
}
