#!/usr/bin/env bash
set -eo pipefail

function msg() {
    local text="$1"
    local div_width="80"
    printf "%${div_width}s\n" ' ' | tr ' ' -
    echo -e "$text"
}

function success_msg() {
    msg "$(printf "\e[1;32m[SUCCESS] %s\e[0m\n" "$1")"
}

function info_msg() {
    msg "$(printf "\e[1;34m[INFO] %s\e[0m\n" "$1")"
}

function warn_msg() {
    msg "$(printf "\e[1;33m[WARN] %s\e[0m\n" "$1")"
}

function error_msg() {
    msg "$(printf "\e[1;31m[ERROR] %s\e[0m\n" "$1")"
}

function compact_success_msg() {
    echo -e "\e[1;32m[SUCCESS] $1\e[0m"
}

function compact_info_msg() {
    echo -e "\e[1;34m[INFO] $1\e[0m"
}

function compact_warn_msg() {
    echo -e "\e[1;33m[WARN] $1\e[0m"
}

function compact_error_msg() {
    echo -e "\e[1;31m[ERROR] $1\e[0m"
}

function pretty_usage() {
  echo -e "\e[1;34m $1\e[0m"
}
